### ISSUE TITLE
[Feat] Mark and exclude IoC which get an delete flag

### ISSUE THREAD

**Issue by 8ear** [DCSO/TIE-Splunk-TA#8]
# Why

An IoC in Splunk has a long retention time, and if a user get today a IoC and tomorrow we know that this is a false positive we require a mechanism to exclude or delete the IoC at every search.

# What

If an IoC get the delete flag exclude or delete the IoC.

Alternative we can run a search once a week to request all IoCs at TIE and check if the IoC have a delete flag and exist the IoC.

# How

n/a

**Comment by geertjanvdk** [comment]
The current implementation with defaults in place, will actually not import non-malicious (severity==0). It will only import >= 1. There is no "deleted flag".

# How

- [] Refactor the current filtering in `tie2index.py` so that it is actually readable.
- [] `setup.xml`: the severity should support ranges and validate them
- [] keep compatible with current configuration, without adding new
- [] document severity ranges in README and in `setup.xml`

**Comment by geertjanvdk** [comment]
We will also support ranges for confidence, then we have it all covered.
